# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: diginbible.study
title: diginbible.study - Seek the Simple Truth. Share the Simple Truth.
use_logo: true
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Seek the simple truths. Share the simple truths. 
    God is love. (1 John 4:16) 
    Love is the intersection of Truth and Grace. (John 1:14; 17)
    Love must be expressed in God’s order. (Matthew 22:37-40)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diginbible.study" # the base hostname & protocol for your site, e.g. http://example.com
# See: https://disqus.com/
disqus_username: diginbiblestudy
twitter_username: SecondPsalms
# github_username:  jekyll

# Build settings
# theme: minima
remote_theme: thiagorossener/jekflix-template

# SASS
sass:
  style: compressed
  
plugins:
  - jekyll-feed
show_hero: true
menu:
  - title: Home
    url: /
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact
#  - title: Feed
#    url: /feed.xml
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
